sudo: false

language:
          - python

python:
          - 2.7
          - 3.6

install:
          - pip install pytest

script:
          - pytest --verbose test-file.py

notifications:
          email: false
          
